package com.monsters.dto.auth;

public enum ContinuationNextAction {
    VERIFY_EMAIL,
    COMPLETE_ELIGIBILITY,
    REVIEW_BIRTHDAY_CORRECTION,
    LINK_GOOGLE_ACCOUNT,
    REACTIVATE_ACCOUNT,
    REVIEW_SUSPENSION,
    REVIEW_DELETION
}
