spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/monsters?useSSL=false&serverTimezone=Asia/Taipei&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:monsters}
    password: ${DB_PASSWORD:monsters}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

